### Sign In

### Validation

### Valid request
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "@asdASDasd1"
}

### Invalid request