packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - argon2
  - prisma
  - sharp
  - unrs-resolver
